- id: doi:10.1007/s00125-024-06152-1
  type: paper
  description: Continuous glucose monitoring
  date: 2024-04-19
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1007%2Fs00125-024-06152-1/MediaObjects/125_2024_6152_Figa_HTML.png?as=webp
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review
